### ISSUE TITLE
How to handle image-loaded ?

### ISSUE THREAD

**Issue by sentoro** [s-yadav/angulargrid#35]
If an image is loaded, i need to change src attribute. Help please, or until image is not loaded, i need to show other image (loading process gif).

**Comment by s-yadav** [comment]
It adds class image-loading while image is loading,  you can add a new loading gif inside your element and toggle display depending on image-loading class. You can also use :after sudo selector to add loading gif on the items while image is loading like

```css
.image-loading:after{
 content : "";
 background : url("loading.gif");
 position : absolute;
 top : 50%;
 left : 50%;
 transform : translate(-50%,-50%)
}
```
